### PR TITLE
support for emulated cards SAK (0x28)

### PR DESCRIPTION
**Pull request by freerider7777**

### CODE REVIEW

**Comment by ikarus23** [comment]
Just out of curiosity, what kind of tag emulates Mifare Classic with an SAK of 0x28?

**Comment by freerider7777** [comment]
Hi! Have a look at your resources :) https://github.com/ikarus23/MifareClassicTool/blob/master/Mifare%20Classic%20Tool/app/src/main/res/values/tag_type_list.xml <string name="tag_0004283833B14A434F50343156323331">JCOP41 v2.3.1, IBM</string>...and below <string name="tag_030428">JCOP31, IBM</string> ... Mine is mastercard credit card with transport application. Tomorrow I'll check this card on S3 9300 (now S3 9301 does not report it as mifare classic, but it's ok for emulated cards)  -- С уважением, Павел   12.04.2016, 23:59, "ikarus" <notifications@github.com>:Just out of curiosity, what kind of tag emulates Mifare Classic with an SAK of 0x28?—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by mklostermeier** [comment]
Hi geri
Ich denke, das sind Java Karten die einfach ein Applet haben, was sich wie Mifare verhält.
Und da kein man nicht einmal sicher sein, dass die UID immer die gleiche ist. Normalerweise wählen solche Applets eine zufällige UID und bauen die dann noch in die Verschlüsselung ein. So hat man bei jeder Connection trotz identischer Karte immer andere Schlüssel.

Gruß Dad 

Gruß Manfred
iPAD Mail

**Comment by freerider7777** [comment]
yep, it's reported as mifare classic card on phones that support emulation cards.

**Comment by ikarus23** [comment]
Merged. Sorry it took me so long...

**Pull request merged**
