### PR TITLE
Add full key set of Russian Troika card and group it

### PR DESCRIPTION
**Pull request by zhovner**
Some of this keys randomly appeared in other groups. I've added a full set and grouped it in one place.

### CODE REVIEW

**Comment by zhovner** [comment]
@iceman1001 done https://github.com/RfidResearchGroup/proxmark3/pull/36

**Comment by iceman1001** [comment]
👍

**Comment by zhovner** [comment]
I found some new keys in @iceman1001 dictionary and added it here.

**Comment by ikarus23** [comment]
Look great, thank you. Merged.

**Pull request merged**
