### PR TITLE
Create values-ru

### PR DESCRIPTION
**Pull request by IIIef**
strings.xml

### CODE REVIEW

**Comment by ikarus23** [comment]
Merged. Thank you!

**Comment by ikarus23** [comment]
I've reverted the commit. The format was broken. Please add an `values-ru` folder and add a translated `strings.xml` in the same format as the original on. I don't think it makes sense to translate files like `tag_type_list.xml` as well.

**Comment by IIIef** [comment]
I do not know how to create a folder correctly

**Comment by IIIef** [comment]
I get the wrong creation of the values-ru folder

**Comment by ikarus23** [comment]
It should have the same structure as `values-es`, for example.

**Pull request merged**
