### PR TITLE
Translations for new version.

### PR DESCRIPTION
**Pull request by nkh0472**

### CODE REVIEW

**Comment by nkh0472** [comment]
There are some little question.

For
`<string name="text_block_0_generated">Block 0 generated</string>`
Does it mean "the data of block 0 has been generated" or "the generated data of block 0"?
I changed the translation from the latter to the former.

For
`<string name="action_generic_converter">Generic Type Converter</string>`
Does "Generic Type Converter" is the converter to change the data from HEX/BIN/… to each other?

For
`<string name="action_cyber_chef">Cyber Chef</string>`
Is it https://github.com/gchq/CyberChef or something like that, so I can simply call it "Cyber Chef" without translation?

**Comment by ikarus23** [comment]
Thanks again for doing all this!

>Does it mean "the data of block 0 has been generated" or "the generated data of block 0"?
I changed the translation from the latter to the former.

The first one!

>Does "Generic Type Converter" is the converter to change the data from HEX/BIN/… to each other?

Yes, this is just a simple/generic/common converter for data types or data representations. Like HEX/ASCII/INT/UINT/INT16/etc.

> Is it https://github.com/gchq/CyberChef or something like that, so I can simply call it "Cyber Chef" without translation?

Yes, Cybe Chef is a "product" name. So there is no need to translate it.

**Comment by nkh0472** [comment]
Now it's finished.

**Comment by ikarus23** [comment]
Thank you!

**Pull request merged**
