### PR TITLE
Added and grouped keys from various cards

### PR DESCRIPTION
**Pull request by zhovner**
Added keys from:

* Strelka card extension
* Moscow public toilets
* Iron Logic object card

All keys grouped in one place and duplicates removed from other sources.

### CODE REVIEW

**Comment by zhovner** [comment]
@iceman1001 Maybe we need one keys database to simplify managing?

**Comment by iceman1001** [comment]
as long its a text file its not a biggie,   its just in pm3 file it has comments etc,  It doesn't need the comma you added in your last push ;)

I am however inclined to use a sqlite DB,  and get a better view of found uid, keys , location,   like Walrus has and  like they suggest in this paper http://ext.delaat.net/rp/2015-2016/p04/report.pdf

**Comment by iceman1001** [comment]
It would be great if MCT, Walrus, Chameleon Mini and PM3 used the same sqllite DB...

**Comment by ikarus23** [comment]
Thanks.

Some thing that bothers me too: All the "unique" keys in the key file. Meaning someone crack their card, added the keys but did not notice the keys were derived and are different on each card. Keys like these really slow down the whole concept of wordlist-based reading.

For example, there are 64 keys for the "Moscow social card", but there is no Mifare Classic tag type with 32 sectors. There are either keys missing (for a 4K tag) or these are the keys of 2 different "Moscow social cards" (with 1K each).  And the reason for two tags to have completely different keys even though they are used for the same application is most likely, they are derived by the UID.

Nevertheless, I really like the idea of a centralized key database. Maybe as a web app which allows users to share there keys and to download them in formats like sqlite, text, csv, etc.

**Comment by zhovner** [comment]
>For example, there are 64 keys for the "Moscow social card", but there is no Mifare Classic tag type with 32 sectors. 
It's a 4K card, but for some sectors default keys are used. 

>And the reason for two tags to have completely different keys even though they are used for the same application is most likely, they are derived by the UID.
There is no two "moscow social cards". One is a public transport card called Troyka, and another social card for students. Two of them uses same keys for several sectors, and also default keys. So I keep only uniq keys in dictionary for each card. 
I'm completely sure, that this keys has not derived by the UID, and all this keys are static and valid for whole system.

**Comment by ikarus23** [comment]
>There is no two "moscow social cards". One is a public transport card called Troyka, and another social card for students. Two of them uses same keys for several sectors, and also default keys. So I keep only uniq keys in dictionary for each card.

Thanks for the clarification. The "two moscow social cards" was just an example to explain my point about card-specific/UID-derived keys in key files. I just wanted to say there is no point to add keys to a shared key file which only work one card.

>I'm completely sure, that this keys has not derived by the UID, and all this keys are static and valid for whole system.

Great! I will merge this pull request.

**Pull request merged**
