### PR TITLE
New function: one-click clone UID to "magic UID" gen2 

### PR DESCRIPTION
**Pull request by smartlockpicking**
Hi,
I have created new function - one click clone UID to "magic UID" gen2 cards.
The gen2 do not need this special "backdoor" commands that are not possible to invoke using Android. Instead, they use simple direct write to block 0. They are available from various sources in China.

Until now it was possible to clone UID to such card by first reading then copying the whole block 0, and that involves several complicated actions. In my new function it is much more convenient - you just need to scan the original card (no need to read, no need to know the keys to sector 0), then place the phone by the "magic" tag and it clones UID automatically. I recorded a short video how it works:
https://www.youtube.com/watch?v=8DnhkdngdU8

Code review/cleanup/doc/new icon may be helpful.
I added it to Tools for now, but I would be happy to use it directly from main menu.

### CODE REVIEW

**Comment by ikarus23** [comment]
Hi Sławek, great to hear from you again. If I remember correctly we've met at DeepSec 2016 :). Thanks for contributing. I really like it. Please give me some time to review and test your code. I really have to make more time for MCT...

Will you be at Troopers in Heidelberg, DE?

**Comment by jslawek** [comment]
Hi Gerhard,
yes we were having good time at Deepsec 2016 :)  I'm not going to Troopers unfortunately, but I will be e.g. at HITB AMS, or HackInParis.
Sure, take your time, I can feel you pretty well regarding this lack of time for developing tools... 
I am rather bad programmer, and I haven't tested this code thoroughly, I also guess some GUI redesign may be needed. Let me know if you need any help, or these "magic gen2" cards for testing, I can ship them to you. 
BTW. would you consider some Ultralight functionality? There are magic Ultralight cards that would be nice to support, too. I can help with that later.

**Comment by ikarus23** [comment]
> I'm not going to Troopers unfortunately, but I will be e.g. at HITB AMS, or HackInParis.

Too bad, but maybe I can make it to HITB.

> I am rather bad programmer, and I haven't tested this code thoroughly, I also guess some GUI redesign may be needed. 

We will see ;) I'm too are not a really good programmer.

> Let me know if you need any help, or these "magic gen2" cards for testing, I can ship them to you.

I should have some "magic gen2" tags. I will check if they are the right ones. I'm pretty sure there are different types of gen2 tags out there.

>BTW. would you consider some Ultralight functionality? There are magic Ultralight cards that would be nice to support, too.

I don't think so. The internals of Mifare Ultralight (e.g. memory organization, keys, etc.) are completely different to Mifare Classic. It would be best if someone creates a dedicated app for Mifare Ultralight. :)

**Comment by jslawek** [comment]
Yes there are various "gen2" tags, some of them work better than the others. I can ship to you a few confirmed working well, just send me the address on priv.
I know Ultralight is different, I was thinking initially about this UID cloning for 7-byte, too. Magic ultralights gen2 support that, and I think they are easier to get than 7-byte S50. And many readers do not check SAK/ATQA, just the UID of anticollision.
Regarding Ultralight there is opensource app made for EMUTAG:
http://www.emutag.com/soft.php
It is not supported any more, and recently pulled out of store, but still works pretty well e.g. for cloning hotel cards. 
Anyway, this is Mifare "Classic" Tool, let's just leave it for now.

**Comment by cosmocain** [comment]
Hello smartlockpicking

I downloaded from the mifare classic tool repository in order to use the new function that you show in the video, but when you download it from: https://github.com/smartlockpicking/MifareClassicTool.git the apk does not appear to load on my smartphone.
can you help me with that?

Thank you

**Comment by jslawek** [comment]
I'm not sure I understand your question @cosmocain . The respository is just a source code, in order to make apk you need to compile this source using e.g. Android Studio. It is not difficult, but if you don't know how to do it, I would suggest to wait for the functionality to be merged.

**Comment by cosmocain** [comment]
hi jslawek has
yes the query was by the repository to find the apk of mifare or with the new function of cloning uid

**Comment by cosmocain** [comment]
@ikarus23 
Dear ,
when do you think you can launch the new update with the function of cloning the uid?

**Comment by ikarus23** [comment]
@cosmocain I hope I will find some time during the Easter holidays (this weekend) or the weekend after that. But since I kind of promised to @jslawek that it will be ready for HackInTheBox AMS the function should be there before May 10 ;)

**Comment by cosmocain** [comment]
@ikarus23 
great I will be attentive to the update, I would also like to touch a point where my mifare card is unable to read sector 4 and 9 to see if they could support me in that too.

**Comment by ikarus23** [comment]
> @ikarus23
> great I will be attentive to the update, I would also like to touch a point where my mifare card is unable to read sector 4 and 9 to see if they could support me in that too.

You are unable to read sector 4 and 9? Do you have the keys? Regardless, this sounds OT. Maybe its best to open new issue.

**Comment by cosmocain** [comment]
@ikarus23 
Hello ,
yes I have most of the keys but the card is blocked and I can not write it when reading the label, sectors 4 and 9 are dead.

Is there any option to reverse this?

I hope you soon launch the new update of MCT with the option to clone the UID
thanking as always.

regards

**Comment by ikarus23** [comment]
I've merged and reworked the PR. It's not completely finished yet (the info buttons do not work). But you can try [this testing version](http://tests.icaria.de/MifareClassicTool-2.2.6-testing1.apk) if you want.

**Comment by ikarus23** [comment]
@cosmocain I do not understand what your issue is.

**Comment by jslawek** [comment]
Cool, I confirm it works with my cards.
Nicely reworked UI, now it is much better than my initial version, thanks! 
The info buttons are not crucial. But let me know if you need any help anyway.

**Comment by ikarus23** [comment]
Great, thanks for testing. 
> Nicely reworked UI

I reworked big parts of the code too. Don't get me wrong. You did everything great, but my code base is badd and it is hard to find the bits I've already implemented. I also added the possibility to choose the key (A or B). I also wanted to add support for 7 bytes UIDs. But this needs some more changes and I'm low on free time. Maybe I will do it in the future. :)

> The info buttons are not crucial.

Yes they are! I think I will have everything ready by the end of this weekend.

**Comment by jslawek** [comment]
Sure, the code needed this rework, now looks much better, too, thanks!
I never had these 7-byte "direct write" magic cards, but I think they are not very common, and I would leave this feature to v2. I was using Ultralight gen2 for this - the same anticollision, works for 7-byte access control as well. That's why I mentioned Ultralight in this thread. 

You are probably right we should educate people on differences between 1st gen "backdoor commands" and 2nd "direct write"  cards. A quick automatic check function to do this would be great. I have heard some of gen2 respond with ATS, but not my ones. So the only way that I am aware to confirm that it is gen2 is to actually write something to block0. And even if you write only e.g. one last byte of block that is actually never used, and then restore it back, that is a bit invasive.

Great to hear you will publish soon! Is this testing apk signed by the same developer key, i.e. will it update via Play Store?

**Comment by ArchangeGabriel** [comment]
I’ve even seen people with 7-byte direct write DESFire EV1 behaving cards. They were definitively rare (I’ve been searching a lot for them some years ago), but maybe not so much anymore.

If people know where to source them, as well as 1K Classic gen2 in card format (all I have are gen1 circle tokens), I’d be interested.

**Comment by cosmocain** [comment]
Good day @ikarus23 
I wanted to make a query because I am using the mct 2.6 testing app but using the clone uid option only copies the first 8 digits it will be possible to copy the entire UID as shown in the attachment where I compared the dumps.

Will it be possible or maybe I did something wrong?

thank you
IMG_20190503_093508

**Comment by ArchangeGabriel** [comment]
But the UID is the first 8 digit (4 bytes). So it works as expected.

**Comment by cosmocain** [comment]
@ArchangeGabriel 
Yes, I'm not subtracting credit to the new function, on the contrary I think it's fantastic that you can clone the uid, I'm just making a reference about it is possible to clone all the uid that appears in the photo that I left in the comment.

**Comment by ArchangeGabriel** [comment]
You can already clone any part of a card with MCT. This new function is just about adding a way to quickly clone the UID only, and I think it does not makes sense to extend it to any further portion of the card (excepted maybe 7 bytes UID, but currently those are not supported at all in the first place).

**Comment by ikarus23** [comment]
@jslawek Checking for gen2 would be great, but I think you've mentioned the only way. For me it is to invasive. Especially because there are tags which are one-time block 0 writable (to trick readers afterwards there are original Mifare Classic tags).
And yes, the testing version is signed with the same key and should update via Google Play once I release the update.

@ArchangeGabriel There are 7 bytes UID changeable Mifare DESFire tags? How do they work? Do they have special command to change the UID?

@cosmocain It looks like you want to clone a full tag. MCT could always do this. You read a tag (save it if you want) and write it to "magic tag 2nd gen" (block 0 writable). If you want to write block 0 only, you can also read it, copy it to your clipboard and write it with the "write block" function. As @ArchangeGabriel said, this new "clone UID tool" is just for convenience.

**Comment by cosmocain** [comment]
@ikarus23 
@ Thanks for answering, I also want to congratulate you for the improved app, by the way I must mention the following:
before you merge with the option to clone uid I made the dumps of the card 1 cloning all its data and then I wrote the card 2 with everything including uid block 0 remaining in the same way or mirrors, but one the card 1 operated without problems However, card 2 told me "Card not enabled" being that they were the same but it is something that I have not been able to understand.

**Comment by ikarus23** [comment]
@cosmocain Sorry, I do not understand what you are saying. Cloning did not work? Are both tags not not the same?

**Comment by cosmocain** [comment]
@ikarus23 
I'll start over .
I made the cloning of a card leaving all the sectors equal.
card 1 passed the test without problems.
card 2 marked me an error when trying to go through the access throwing as a message: card not enabled.

the strange thing is that I made an exact cloning.

**Comment by ikarus23** [comment]
Does the diff tool say each sector is identical?

**Comment by cosmocain** [comment]
Yes when comparing the dumps all sectors and blocks are identical, so I do not know what the real reason at the time of the cloning will be?

**Comment by ikarus23** [comment]
In this case it seams like the reader at the access control point is checking some other thinks. Maybe the ATS or the SAK is different. Or maybe the tag does support some backdoor command and the reader checks for it.

**Comment by ikarus23** [comment]
The clone UID feature has now been released.

**Comment by ArchangeGabriel** [comment]
@ikarus23 I’ve found this website when looking for Gen2 cards: https://www.rfxsecure.com/magic-uid-changeable-rfid-cards/.

They have https://www.rfxsecure.com/product/7byte-uid-changeable-card-with-desfire-sakatqa/ especially. It’s in their Gen2 category, so I would guess direct write. I’ll also ask someone I know has one where they got it from and how it works and update here upon receiving the answers.

**Comment by ikarus23** [comment]
@ArchangeGabriel Sounds interesting. Thanks. :)

**Comment by ArchangeGabriel** [comment]
@ikarus23 The person I know got them from https://lab401.com/products/desfire-compatible-emulator-uid-modifiable and those are clearly backdoor ones.

**Comment by ikarus23** [comment]
@ArchangeGabriel I see. They use a custom command to change the UID. Makes sense. And it looks like it is possible to send this command from an Android app. MIFARE DESFire is not in the scope of MCT but it should be possible to write an app for this. ;)

**Comment by cosmocain** [comment]
Screenshot_2019-05-06-06-48-01

@ikarus23 Good afternoon, along with greet you, I inform you that I am occupying the new version of mct 2.3.1, using the function clone uid not copy as it should be and I am using cards with uid that allows the change in block 0 I will be doing something wrong, which does not work for the other cards?

**Comment by ikarus23** [comment]
@cosmocain Well, it seams like you do not have a 2nd gen card. It is most likely a 1st gen card. Manufacturers start to sell the Android compatible tags as "MCT" compatible. Check aliexpress and read the feedback of other users. Have look [here](https://www.aliexpress.com/wholesale?catId=0&SearchText=mct).

**Comment by cosmocain** [comment]
@ikarus23 It's funny because in another card I could make the uid change using the new clone function.
and they are all the cards bought from the same provider, but as I say some, I could change them and others could not.

thanks

**Pull request merged**
