### PR TITLE
values-ru

### PR DESCRIPTION
**Pull request by IIIef**

### CODE REVIEW

**Comment by IIIef** [comment]
Translation into Russian

**Comment by ikarus23** [comment]
Hi. First of all: thank you for contributing. However, the file currently breaks the build process. There are values in there that are not present in the original strings.

**Comment by IIIef** [comment]
> Привет. Прежде всего: спасибо за вклад. Однако в настоящее время файл прерывает процесс сборки. Там есть значения, которых нет в исходных строках.

Thanks, I figured it out)

**Comment by ikarus23** [comment]
Sorry, but this is still all over the place. Did you merge resource files into one (`strings.xml` and `access_conditions.xml`)? They should be formatted exactly like the original and be in the same file.

**Pull request closed without merging**
