### PR TITLE
Make NFC optional

### PR DESCRIPTION
**Pull request by ravkr**
As this app supports external NFC readers, it should be possible to find it on Google Play.

### CODE REVIEW

**Comment by ikarus23** [comment]
Have you tried MCT with external readers? As far as I know there are still a lot of issues with [External NFC](https://play.google.com/store/apps/details?id=eu.dedb.nfc.service). Or is my knowledge outdated? What setups have you tried?

**Comment by ravkr** [comment]
Yes, I've been using it with external reader for more than year, and almost everything works fine (except for writing block 0 on Chinese cards).
Phone: Xiaomi Redmi 5 Plus
Reader: ACR122

**Comment by ravkr** [comment]
@ikarus23

**Comment by ikarus23** [comment]
Ok. In that case I might drop the NFC requirement. I'm a bit cautious with this, because I get a lot of support requests. And if it will only work with a specific reader + additional app, more people will write support requests because they are too stupid to read the readme or to google the web. ;)

**Comment by ikarus23** [comment]
After giving it some further thought, I've come to the conclusion not to drop the NFC requirement. I'm sorry, but there are just to many stupid people out there giving MCT bad reviews because "it is not working". Without the requirement they will become even more. Also, this will create too much support request and likely even for software (like External NFC) which I'm not the author of.

People with a technical background can always download the app from https://www.icaria.de/mct/releases/. Also there might be an automated way. MCT is on F-Droid (open source app store). This store has automatic update features and the option "Include incompatible versions". I never tried it, but it might be an automated way to have an up-to-date MCT on a device with no NFC.

**Pull request closed without merging**
