### PR TITLE
Adding new translating & reorder strings.

### PR DESCRIPTION
**Pull request by nkh0472**
First, all of the English strings from /app/src/main/res/values/strings.xml has been translated. The original file contains 291 strings, and I added & translated new 93 strings from the English file, and improved some translating too. 
Besides, I reordered the strings to keep consistency with English strings.xml, which could be very helpful to stay the latest for further updates.

However, I don't have any experience with compelling Android apps, so the above changes is never been tested.
It's very important to test this new translate file, to avoid full screen of R#%#&#&*)@(IDHDBKJB. ^^

### CODE REVIEW

**Comment by nkh0472** [comment]
New strings from the English file are listed as below:

title_activity_clone_uid
title_activity_import_export_tool
title_activity_uid_log_tool
title_activity_data_conversion_tool
text_choose_key_files
text_invalid_data
text_clone_uid_info
text_uid_to_clone
text_clone_uid_manufacturer_block_rest
text_write_key
text_status_log
text_use_uid_of_scanned_tag
text_block_0_calculated
text_waiting_for_magic_tag
text_writing_block_0
text_no_errors_on_write
text_rescan_tag_to_check
text_checking_clone
text_clone_successfully
text_uid_match_error
text_clone_error
text_uid_length_error
text_select_file
text_select_directory
text_choose_dump_file
text_export_convert_dest_info
text_random_uid
text_no_uid_logs
text_not_ascii
text_convert
text_ascii
text_hex
text_bin
text_dec_be
text_dec_le
text_invalid_ac
action_retry_authentication
action_use_internal_storage
action_autostart_if_tag_detected
action_show_clone_uid
action_show_import_export_tool
action_show_uid_log_tool
action_show_data_conversion_tool
action_install_external_nfc
action_start_external_nfc
action_external_nfc_is_running
action_clone_uid
action_file_type_mct
action_file_type_keys
action_file_type_mdf_bin
action_file_type_eml
action_file_type_json
action_file_type_bin
action_import_dump
action_export_dump
action_import_keys
action_export_keys
info_not_bin_data
info_share_error
info_retry_authentication_count_error
info_mapping_no_keyfile_selected
info_mapping_no_keyfile_found
info_rest_of_block_0_length
info_incorrect_key
info_file_exported
info_file_imported
info_convert_error
info_incomplete_dump
info_error_reading_file
info_random_uid
info_invalid_key_file
dialog_no_mfc_support_device
dialog_no_mfc_support_tag
dialog_static_ac
dialog_retry_authentication_title
dialog_retry_authentication
dialog_use_internal_storage_title
dialog_use_internal_storage
dialog_no_nfc_support_title
dialog_no_nfc_support
dialog_start_external_nfc_title
dialog_start_external_nfc
dialog_info_external_nfc_title
dialog_info_external_nfc
dialog_gen2_tags_info_title
dialog_gen2_tags_info
dialog_rest_of_block_0_title
dialog_rest_of_block_0
dialog_key_for_block_0_title
dialog_key_for_block_0
hint_hex_4_7_10_byte
hint_custom_sector_count
hint_custom_retry_authentication_count

**Comment by ikarus23** [comment]
Thank you for contributing and thank you for reorganizing everything! It's hard for me to validate, if everything is displayed the correct way. However, it is not hard for me to build a test version ;). You can download it from [here](http://tests.icaria.de/MifareClassicTool-3.1.2-test1.apk). Please install it and validate if everything looks good (or good enough).

**Comment by nkh0472** [comment]
The test version showed exactly what was expected. However, I found that the old translation's quality is still very poor, and every sentence can see the traces of machine translation. I will fully rewrite them tomorrow.

**Comment by ikarus23** [comment]
Wow, that is great! Thank you so much for doing this.

**Comment by nkh0472** [comment]
Main work of this has been completed, and I plan to check if any symbols cannot be displayed. (I saw some Unicode in the strings such as &#8226, I’m not sure every symbol I write could be displayed. For example, I use CUID/FUID instead of magic card (gen 2) because the former is used in China, here, the symbol "/" might be a problem.

Besides, I don't quite understand the meaning of some strings. Can you explain them a little bit?

```
<!-- Texts (labels etc.) -->
<string name="text_caption_title">Caption</string>
<string name="text_ac_decr">Decr./Trans./Rest.:</string>
<string name="text_vb_what">What:</string>
<string name="text_vb_value">Value:</string>
<string name="text_vb_orig">Original:</string>

<!-- Actions (Buttons, Checkboxs, etc. -->
<string name="info_valid_dump_double_sector">Error: Multiple times the same sector number</string>
```

**Comment by ikarus23** [comment]
Thank you for the update!
>  For example, I use CUID/FUID instead of magic card (gen 2)

Be careful with that. There are a lot of different CUID tags out there. But only gen2 tags work with this app. Other CUID tags do not work. So "gen 2" is very important (see https://github.com/ikarus23/MifareClassicTool#general-information (point nr. 4) and https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/magic_cards_notes.md (section about MIFARE Classic)).

`<string name="text_caption_title">Caption</string>`
Caption as in "map key" or "map legend". Basically the section where it is described what is what. In case of MCT this is the "header" over the colors in the dump editor, explaining what color is what.

`<string name="text_ac_decr">Decr./Trans./Rest.:</string>`
Abbreviations of "decrement", "transfer" and "restore". These are three MIFARE Classic specific commands. They are called this way in the official datasheet. I don't know if there is good translation.

`<string name="text_vb_what">What:</string>`
"what" like in asking for the subject. "what was the original value". In this context it is just the header of a table.

`<string name="text_vb_value">Value:</string>`
Another table header. Just to show what the "value" is after converting it. So in the context of digit or a number. "a=10 -> variable a has a value of 10".

`<string name="text_vb_orig">Original:</string>`
Another table header. Just to show what the "original" value was before it was converted. ("original" -> convert "value" -> result).

`<string name="info_valid_dump_double_sector">Error: Multiple times the same sector number</string>`
An error message stating, that there where more than one sector in this dump, with the same number. For example, if there is a sector 5 and another sector 5 in one dump, this will be an error.

I hope this helps.

**Comment by ikarus23** [comment]
Updated version for testing: http://tests.icaria.de/MifareClassicTool-3.1.2-test2.apk

**Comment by nkh0472** [comment]
Those descriptions help me a lot!
But I still feel a little confused about this (that actually because I couldn't find the table where using this string):

> `<string name="text_vb_what">What:</string>`
> "what" like in asking for the subject. "what was the original value". In this context it is just the header of a table.

Should I translate it to "position" or "the name of value (such as abc or xyz)"? I translate it into position for now. 

There is no problem caused by symbols in  MifareClassicTool-3.1.2-test2.apk. And I've further corrected other inappropriate translations.

**Comment by nkh0472** [comment]
Thank you for your patient reply to me all the time!

So far, everything is displayed correctly. I don't think it is necessary to compile the third test version to confirm whether the display is ok. And I'll edit this xml file if there is any translating problem.

Just out of curiosity, how long does it take to compile this app on your computer?

**Comment by ikarus23** [comment]
Thank you. "position" is fine. It's even better than "what". I guess the best would be "location" as in "location on the tag" because its the header for where the value block was found on the tag.
Screenshot_20201024-225920

**Comment by ikarus23** [comment]
Are you finished translating? If so, I will merge it.

**Comment by nkh0472** [comment]
It's OK to merge.

The meaning as "the act of putting something in a certain place" or "the location of someone or something is their exact position" of position and location, is the same in Chinese. :)

**Comment by ikarus23** [comment]
Thanks. Merged.

**Pull request merged**
