### PR TITLE
Update COMPATIBLE_DEVICES.md

### PR DESCRIPTION
**Pull request by HrBDev**

### CODE REVIEW

**Comment by ikarus23** [comment]
Thanks! I don't want to sound too strict, but can you please add a space before the "(" ?

**Comment by HrBDev** [comment]
of course, I don't know how I missed the space.
Also, I've got a quick question:
Are you still interested in developing this app? like refactoring or adding support for newer Mifare cards? or a whole new app using the Mifare provided library?

**Comment by HrBDev** [comment]
Thanks for the answers.

**Comment by ikarus23** [comment]
Thanks.

**Pull request merged**
