### PR TITLE
Update INCOMPATIBLE_DEVICES.md

### PR DESCRIPTION
**Pull request by ceres-c**
Added a couple of tested devices

### CODE REVIEW

**Comment by ikarus23** [comment]
Thanks for participating! I added most of the devices to the list of compatible devices.
Could you explain what you mean by "partially working" (Huawei P10)?

**Comment by ceres-c** [comment]
It does work when reading or writing but seldom it fails when writing multiple sectors (more than 5) at the same time.  We haven't investigated the causes but it might be a timing error.

Also, recently we tried a ZTE Axxon 7 and a Honor 9 and they are both working. You might want to add those too without me creating a new PR :-)

**Comment by ikarus23** [comment]
Thanks for the quick feedback. This possible timing issue does indeed sound interesting.
Also, thanks for the update on the ZTE Axxon 7 and the Honor 9. I will add them right away.

Off topic: What do you mean by "recently we tried..."? Do you have access to a large number of different Android devices? And you test if they all work with Mifare Classic? ;)

**Comment by ceres-c** [comment]
Oh, I almost forgot: we found a mifare plus in emu mode, the tag was ignored by the nexus 6p as it was a mifare plus, while on both the oneplus 5T and the ZTE Axxon 7 it was treated by your app as it was a normal mifare classic. Is this the correct behavior or is it worth to open a new issue?

**Comment by ceres-c** [comment]
> Thanks for the quick feedback. This possible timing issue does indeed sound interesting.

You're welcome, it's the least I can do. Apart from buying the donate version, but I've already done that  ;-) If you want to dig deeper into this issue tell me what can I do.

> Also, thanks for the update on the ZTE Axxon 7 and the Honor 9. I will add them right away.

You're welcome! I almost forgot about this PR

> Off topic: What do you mean by "recently we tried..."? Do you have access to a large number of different Android devices? And you test if they all work with Mifare Classic? ;)

Yeah... I have a couple of friends and we all like to play with RFID. Also, NFC tastes good, if you know what I mean...

**Comment by ikarus23** [comment]
Also very interesting. But I don't think it is because of MCT that the tag was not recognized correctly. Most of this part is handled by Android. Well, I have some code in the app for identification purposes as well, but it's the same code for the Nexus 6P and every other device. However, I tweaked that code a bit. The new code is now part of the latest release. Maybe it will work now... There wasn't a lot of testing... (https://github.com/ikarus23/MifareClassicTool/issues/131 was the issue here)

>Yeah... I have a couple of friends and we all like to play with RFID. Also, NFC tastes good, if you know what I mean...

That's great! And yes, I know what you mean ;)

**Comment by ceres-c** [comment]
I'll test ASAP (tonight possibly) and let you know if my problematic tag now works. I have not tracked down the reason behind our problem, but I believe you are right when you say it's android's fault. On the nexus mifare was **not** listed among the supported standards for that tag, while on the other devices it was listed.

Still I'll test some different tags to check whether your updated code is working :-)

**Comment by ikarus23** [comment]
Cool, thanks. And don't worry on ASAP. Whenever it suits you best!

And yes, the Nexus 5X / 6P are known for issues with Mifare Classic. I have a 5X myself with a very strange bug: https://github.com/ikarus23/MifareClassicTool/issues/106. Not sure if this affects the 6P as well.

**Comment by ceres-c** [comment]
Tested and does not fix the 6P problem ;-)

**Comment by ikarus23** [comment]
Well, this is really weird... So what you are saying is: This tag has a SAK of 28 on other devices, but on the Nexus 6P its SAK is 20?

**Comment by ceres-c** [comment]
Exactly
I haven't checked in the datasheet if I'm right, but I believe 28 means 20 (mifare plus) + 8 (mifare classic), so mifare classic in emu mode. The 6P uses a NXP PN548, being it made by NXP, it should be 100% compatible with NXP tags, but... I don't know if reporting the tag as a mifare plus is the chip being overzealous, or plainly wrong

**Comment by ikarus23** [comment]
Hmm... very interesting. And also very annoying. There are so much bug in the Android NFC world!
Also, you are right. If there is no "8" (SAK bit 4 = 1) a tag can not be a Mifare Classic tag (according to [AN10834](https://www.nxp.com/docs/en/application-note/AN10834.pdf) page 7).

**Comment by ceres-c** [comment]
It turns out I was wrong in my assumption. SAK 28 means SmartMX with MIFARE 1K, according to the datasheet published by NXP that you linked.
My phone is still wrong when reporting the SAK, but this is not a Mifare Plus SL1.

**Comment by ikarus23** [comment]
Oh, yes, forgot to mention that. But still, it should be a Mifare Classic compatible tag.

**Comment by ba1atu** [comment]
Its ZTE Axon 7, not "Axxon". And its incompatible. I have the A2017U (US variant), with Android 7.1 and when i touch a tag, it makes the notification sound multiple times, after that i get the message "New tag detected", but the notification sound repeats, and it redetects the tag. It goes on like this, so i think the device is incompatible, or maybe its the android version.

**Comment by ceres-c** [comment]
Well, I guess I do not agree...
MifareRead
Phone info (Hardware version is A2017G, but it's using the US rom, so it reports A2017U)
PhoneInfo

**Comment by ba1atu** [comment]
Thanks for the reply. I will see what i can do. Maybe flash LineageOS or make of video of how the app performs for me, for your better understanding.

**Pull request closed without merging**
