### PR TITLE
Update COMPATIBLE_DEVICES.md

### PR DESCRIPTION
**Pull request by netvader**
MCT can read and write classic cards with:
Google Nexus 5x (Android 8.1)
Google Pixel 3 (Android 9)

### CODE REVIEW

**Comment by ikarus23** [comment]
Thanks for contributing, but I'm not sure if I will add the Nexus 5x to the list of compatible devices. I own one and it has a bug described in https://github.com/ikarus23/MifareClassicTool/issues/106. However, it works OK for reading when using the retry authentication option. But sometimes I have trouble writing.

**Comment by jepeto123** [comment]
One question, I need to read a specific sector (8), I can read all sectors except 0 to 8, and I can not find any way to read them, if you could help me or inform me how I could get it, you would help me a lot. 
Thank you.

**Comment by ikarus23** [comment]
@jepeto123 You need the key(s)! If you don't have them you can try to crack them. Check out the [Getting Started](https://github.com/ikarus23/MifareClassicTool#getting-started) section.

**Comment by jepeto123** [comment]
@ikarus23 
Yes, I have both keys, but when reading the block it takes me to the following method:

    byte [] transceive (byte [] data, boolean raw) throws IOException {
        checkConnected ();

        try {
            TransceiveResult result = mTag.getTagService (). Transceive (mTag.getServiceHandle (),
                    data, raw);
            if (result == null) {
                throw new IOException ("transceive failed");
            } else {
                byte [] result2 = result.getResponseOrThrow ();
                return result2;
            }
        } catch (RemoteException e) {
            Log.e (TAG, "NFC service dead", e);
            throw new IOException ("NFC service died");
        }
    }
The following error occurs: java.io.ioexception: transceive failed.

and in the result2 I skip the catch. I do not know if there is something wrong in that method but I can not read the sector, I bought in your application with the keys I had and I got it right but in my app I do not know why it fails. If you can help me with anything, I'd really appreciate it. Thanks

**Comment by millenod** [comment]
Please add this phone as compatible :
Commercial name : Samsung Galaxy S7 Edge (Exynos) 
Device name : SM-G935F (for International & Canada)
Alternate device name : hero2lte
Tested on Android version 9 (LineageOS 16 - 20190609)

This is the test I've done:
- Add a file with keyA and keyB
- Read a mifare classic 1k tag using the right key file: OK
- Write a dump to this Mifaire Classic 1k Tag suring the right key file : OK

**Comment by netvader** [comment]
my request is obsolete, i have to test it even more closely, therefore i close my pull request

**Pull request closed without merging**
