### PR TITLE
Send nfca commands

### PR DESCRIPTION
**Pull request by Xoib**
Hello @ikarus23,

Is there any reasons you didn't merged this feature?

### CODE REVIEW

**Comment by ikarus23** [comment]
Hi @Xoib,
yes, I did not merge it because of all the limitations that made this feature unattractive for using it in combination with MIFARE Classic tags. At least this is what I remember ;) You can read about my struggles in some [old post at the proxmark forum](http://www.proxmark.org/forum/viewtopic.php?pid=7175#p7175) (May 2013).

**Comment by Xoib** [comment]
About the first issue, the added CRC breaking the ANTICOLL 9320 for example, it should be handled directly by the nfc chip, you shouldn't need to care about it on the code side, maybe it wasn't the case at the time.

Regarding the second one, I am not sure but for example in my case I don't care ignoring the exception of the tag response (lacking CRC) of the ANTICOLL and SELECT_UID answers.

```
pm3 --> hf 14a raw -c -s 10 00 00
received 4 octets
65 6B CA D1
received 10 octets
08 00 00 00 65 6B CA D1 00 53
pm3 --> hf list 14a
Recorded Activity (TraceLen = 111 bytes)

Start = Start of Start Bit, End = End of last modulation. Src = Source of Transfer
iso14443a - All times are in carrier periods (1/13.56Mhz)

      Start |        End | Src | Data (! denotes parity error)                                   | CRC | Annotation         |
------------|------------|-----|-----------------------------------------------------------------|-----|--------------------|
          0 |        992 | Rdr |52                                                               |     | WUPA
       2228 |       4596 | Tag |04  00                                                           |     |
       7040 |       9504 | Rdr |93  20                                                           |     | ANTICOLL
      10676 |      16564 | Tag |65  6b  ca  d1  15                                               |     |
      18944 |      29472 | Rdr |93  70  65  6b  ca  d1  15  a5  7f                               |  ok | SELECT_UID
      30644 |      34228 | Tag |00  fe  51                                                       |     |
      47104 |      53024 | Rdr |10  00  00  81  20                                               |  ok |
      54196 |      65780 | Tag |08  00  00  00  65  6b  ca  d1  00  53                           |  ok |
```

Unless we need to rewrite the handling of the exception at the lower level of the function in order to not stop the communication with the tag... That would imply to compile a new nfc lib for android.

**Comment by ikarus23** [comment]
I think the CRC stuff is still an issue today.
1. Adding CRC to every command breaks MIFARE Classic commands.
2. Throwing that exception for wrong CRCs results in the tag being lost.
3. Exception handling is done by Android (in the deeper levels).

Maybe I'm wrong, but until not proven otherwise I don't think I will add that "useless" feature.

**Comment by Xoib** [comment]
Well I understand.
Finally, for my little use case it is working enough but I had to patch the internal nfc lib.

**Comment by ikarus23** [comment]
Patching the lib sounds painful. Just out of curiosity, what are you working on?

**Comment by Xoib** [comment]
Some no-mifare device I have to deal with. Custom protocol over iso1444a though, lucky me!

**Comment by Xoib** [comment]
Btw the patch was only needed on my Nexus 5x (because of the NXP PN548 chip) and not on my Nexus 4 (thanks to the Broadcom 20793S chip). I write that here in case someone need the information.

**Comment by dboss313** [comment]
Ikarus... possible to send me complete modified apk of this? Appreciate it bosscoe313@gmail.com

**Comment by ikarus23** [comment]
@dboss313 I no longer have the compiled version, but you can check out the branch and compile it yourself.

**Pull request closed without merging**
