### PR TITLE
Add Pixel 6a & Pixel 8a to COMPATIBLE_DEVICES.md

### PR DESCRIPTION
**Pull request by taivlam**
I've tested both the Pixel 6a and Pixel 8a with the Metrodroid app.

### CODE REVIEW

**Comment by ikarus23** [comment]
Thanks! Would you mind sorting the 8a after the normal 8? Sorry, I'm picky :)

**Comment by taivlam** [comment]
1.  I've made the changes.
2.  Also, random question: does it really matter that the Pixel 8 series have to be on Android 15+?  It's because I'm working with the assumption that users generally would want the latest OEM supported version of Android on their devices.

**Comment by taivlam** [comment]
To follow the ordering of the Pixel 8a, I also placed the Pixel 6a after the Pixel 6.

**Comment by ikarus23** [comment]
First of all: Thank you so much! Looks great!

Regarding your question: Unfortunately yes. The MIFARE Classic support for Pixel 8 devices was broken and then fixed with Android 15. It took over a year... You can read all about it in https://github.com/ikarus23/MifareClassicTool/issues/441. That is way it is explicitly listed there. But yes, I hope everybody is using the latest version provided. There are also rare cases of MIFARE Classic no longer working after an Android update. Fortunately, in most cases it is stable. If a device is released with MIFARE Classic support, it works right away and stays that way.

**Pull request merged**
